Update deploy.yml
add build and scp action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,11 +8,26 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
+    if: |
+      contains(github.event.head_commit.message, 'deploy') || 
+      contains(github.event.head_commit.message, 'release')
+    
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Authenticate with GCP
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 'latest'
+
+      - name: Build vue
+        run: |
+          cd veganofficialweb
+          npm ci
+          npm run build-only
+
+      - name: Auth with GCP
         uses: google-github-actions/auth@v2
         with:
           credentials_json: ${{ secrets.GCP_SA_KEY }}
@@ -20,16 +35,41 @@ jobs:
       - name: Setup Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v2
 
-      - name: Test SSH Connection via IAP
+
+      - name: SCP Transfer vue File via IAP
+        run: |
+          gcloud compute scp -r veganofficialweb/dist/ ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }}:~/tmp/uploads/dist \
+              --zone=${{ secrets.GCE_ZONE }} \
+              --tunnel-through-iap \
+              || exit 1
+
+      - name: SSH Connection via IAP
         run: |
           gcloud compute ssh ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }} \
               --zone=${{ secrets.GCE_ZONE }} \
               --tunnel-through-iap \
-              --command "echo 'SSH Connection Successful'"
-
-      - name: Test SCP File Transfer via IAP
+              --command "
+              cd ~/app/sp01_VeganWebsite/veganWebServer &&  
+              git pull origin main &&        
+              npm install &&
+              sudo cp -r ~/tmp/uploads/dist/* /var/www/html/dist &&
+              pm2 restart all
+              "
+              
+      - name: Health Check
         run: |
-          echo "This is a test file" > testfile.txt
-          gcloud compute scp testfile.txt ${{ secrets.VM_USER }}@${{ secrets.GCE_INSTANCE_NAME }}:~/tmp \
-              --zone=${{ secrets.GCE_ZONE }} \
-              --tunnel-through-iap
+          max_retries=5
+          counter=0
+          until curl -f https://${{ secrets.APP_DOMAIN }} || [ $counter -eq $max_retries ]
+          do
+            echo "Attempt $counter: Waiting for service to be up..."
+            sleep 10
+            counter=$((counter + 1))
+          done
+          
+          if [ $counter -eq $max_retries ]; then
+            echo "Health check failed after $max_retries attempts"
+            exit 1
+          fi
+          
+          echo "Service is up and running!"
